from tkinter import *
class ImgCryptApp():
    def __init__ (self):
        window = Tk()
        options = ["test", "test input 1"]
        clicked = StringVar()
        clicked.set("test")
        window.title("Image Crypt")
        top = Label(text="UI-02 Img Crypt Action Area", justify = "left")
        top.grid(row = 0, column = 0, sticky = 'w')
        txt = Text(height = 10, width = 50)
        txt.grid(row = 1, column = 0)
        loadImg = Button(text = "UI-05 Load Image", width = 45)
        loadImg.grid(row = 2, column = 0, sticky = 'sw')
        loadTxt = Button(text = "UI-07 Load Text", width = 15)
        loadTxt.grid(row= 2, column = 0, sticky = 'se')
        saveImg = Button(text = "UI-6 Save Image", width = 45)
        saveImg.grid(row =3, column = 0, sticky = 'nw')
        saveTxt = Button(text = "UI-08 Save Text", width = 15)
        saveTxt.grid(row = 3, column = 0, sticky = 'ne')
        settingsLbl = Label(text = "UI-03 Settings Area")
        settingsLbl.grid(row = 4, column = 0, sticky = 'nw')
        #placement here needs work, too tired rn
        upLabel = Label(text = 'UIL-01 User Profile Label')
        upLabel.grid(row = 5, column = 0, sticky = 'w')
        upDrop = OptionMenu(window, clicked, *options)
        upDrop.grid(row = 6, column = 0, sticky = 'w')
        nUserProfile = Button(text = "New")
        nUserProfile.grid(row=6, column= 0)
        dUserProfile = Button(text ="Del")
        dUserProfile.grid(row = 6, column=0, sticky = 'w')
        charsPerPixelLabel = Label(text = "UIL-03 Characters Per Pixel")
        charsPerPixelLabel.grid(row = 7, column=0, sticky = 'w')
        charsPerPixel = OptionMenu(window, 'test', *options)
        charsPerPixel.grid(row = 8, column = 0, sticky = 'w')
        colorSettingsLabel = Label(text = "UIL-05 Color Settings Label")
        colorSettingsLabel.grid(row = 9, column = 0, sticky = 'w')
        colorSettings = OptionMenu(window, 'test', *options)
        colorSettings.grid(row = 10, column = 0, sticky = 'w')
        #placement needs some work, but I'm too tired to work that out now, same with the buttons for User Profiles
        spLabel = Label(text = 'UIL-02 Settings Profile Label')
        spLabel.grid(row = 5, column = 0, sticky = 'e')
        spDrop = OptionMenu(window, clicked, *options)
        spDrop.grid(row = 6, column = 0, sticky = 'e')
        nSettingsProfile = Button(text = "New")
        nSettingsProfile.grid(row=6, column= 0)
        dSettingsProfile = Button(text ="Del")
        dSettingsProfile.grid(row = 6, column=0)
        sSettingsProfile = Button(text = 'Save')
        sSettingsProfile.grid(row = 6, column = 0, sticky = 'e')
        pixelSpacingLabel = Label(text = "UIL-04 Pixel Spacing")
        pixelSpacingLabel.grid(row = 7, column=0, sticky = 'e')
        pixelSpacing = OptionMenu(window, 'test', *options)
        pixelSpacing.grid(row = 8, column = 0, sticky = 'e')
        hashKeyLabel = Label(text = "UIL-06 Hash Key")
        hashKeyLabel.grid(row = 9, column = 0, sticky = 'e')
        hashKey = Entry()
        hashKey.grid(row = 10, column = 0, sticky = 'e')
        imgPlaceholder = Label(text = 'Placeholder for image preview')
        imgPlaceholder.grid(row = 3, column= 1)
        window.mainloop()
img = ImgCryptApp()