'Author: Andrew Bounds
'Last Edit: 2022-05-10
@startuml Creating User Profiles
title Creating User Profiles
header Last Edit: 2022-10-05

Actor       User                            as  user
participant "ImageCryptApp()"               as  gui
Database    "ProfileManagementService()"    as  pms

user -> gui ++ : Request New Profile
gui -> gui ++ : Prompt Profile Name
user -> gui : Input Profile Name
gui --

gui -> pms ++ : CreateUserProfile(string name)\n:UserProfile p
pms --

gui -> gui : SetActiveUserProfile(p)

@enduml